version: '3.8'
services:
  test-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: confidence_picks_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_user -d confidence_picks_test"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test_db_data:
